SELECT YEAR(B.SALES_DATE) AS YEAR,
       MONTH(B.SALES_DATE) AS MONTH,
       COUNT(DISTINCT(B.USER_ID)) AS PUCHASED_USERS,
       ROUND(COUNT(DISTINCT(B.USER_ID)) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PUCHASED_RATIO
       
       
FROM USER_INFO A,ONLINE_SALE  B
WHERE A.USER_ID = B.USER_ID
 AND YEAR(A.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH